#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["src/EnvironmentSensorDashboard.API/EnvironmentSensorDashboard.API.csproj", "src/EnvironmentSensorDashboard.API/"]
COPY ["src/EnvironmentSensorDashboard.Data/EnvironmentSensorDashboard.Data.csproj", "src/EnvironmentSensorDashboard.Data/"]
COPY ["src/EnvironmentSensorDashboard.Domain/EnvironmentSensorDashboard.Domain.csproj", "src/EnvironmentSensorDashboard.Domain/"]
RUN dotnet restore "EnvironmentSensorDashboard.API/EnvironmentSensorDashboard.API.csproj"
COPY . .
WORKDIR "/src/EnvironmentSensorDashboard.API"
RUN dotnet build "EnvironmentSensorDashboard.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EnvironmentSensorDashboard.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EnvironmentSensorDashboard.API.dll"]