#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["EnvironmentSensorDashboard.Poller/EnvironmentSensorDashboard.Poller.csproj", "EnvironmentSensorDashboard.Poller/"]
COPY ["EnvironmentSensorDashboard.Data/EnvironmentSensorDashboard.Data.csproj", "EnvironmentSensorDashboard.Data/"]
COPY ["EnvironmentSensorDashboard.Domain/EnvironmentSensorDashboard.Domain.csproj", "EnvironmentSensorDashboard.Domain/"]
RUN dotnet restore "EnvironmentSensorDashboard.Poller/EnvironmentSensorDashboard.Poller.csproj"
COPY . .
WORKDIR "/src/EnvironmentSensorDashboard.Poller"
RUN dotnet build "EnvironmentSensorDashboard.Poller.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EnvironmentSensorDashboard.Poller.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EnvironmentSensorDashboard.Poller.dll"]